### ISSUE TITLE
Tidsramme på rapport

### ISSUE THREAD

**Issue by manjan5** [manjan5/smerteregisteret#1]
Rapporten skal kun vise for et år (kalenderår) av gangen. Bruker skal kunne velge hvilket år den vil se. Hvis den velger 2018, vises hele året. Hvis den velger 2019 vises (i dag) t.o.m. august. Den må stå i rapporten hvilken tidsperiode som er valgt (i overskrift eller lignende).

**Comment by areedv** [comment]
Koden må kunne håndtere manglende data/deler av årssett. Om det ut fra brukervalg blir så lite data at rapporten ikke kan lages så må dette feilhåndteres i koden slik at rapporten ikke knekker men viser at den har for lite data til å lage figurer/tabeller/tekst. Dette vil typisk oppstå når brukeren den5. januar ber om data for inneværende år

**Comment by manjan5** [comment]
Are har fikset dato (år)
