### ISSUE TITLE
Sykehusnavn som gjenspeiler lokale data

### ISSUE THREAD

**Issue by manjan5** [manjan5/smerteregisteret#2]
Det skal kun være mulig å hente denne rapporten for det sykehuset man tilhører ettersom det er lokale data. Er dette lagt inn @areedv ? 

Tenker at sykehusnavnet skal stå i overskriften, selv om det ikke vil variere for de som henter den ned (slik som f.eks år kan gjøre).

**Comment by areedv** [comment]
Ja, det bør være mulig og jeg tror denne henger sammen med #3
