### ISSUE TITLE
Avdelingsnavn i rapport

### ISSUE THREAD

**Issue by manjan5** [manjan5/smerteregisteret#3]
Er sak åpen i jira som ber om å få datadump med avdelingsnavn. Når denne er klar skal en avdelingsoversikt (antall per avdeling o.l.) med i rapporten i en tabell og evnt. figur. Dette er det eneste som mangler i rapporten, men rapporten kan leveres uten dette foreløpig.

**Comment by areedv** [comment]
Inntil vi har slike data (levert av HNIKT) er det en mulighet å lage interne data i R pakken som mapper kode og avdeling, og som benyttes midlertidig for å produsere rapporten(e)

**Comment by manjan5** [comment]
Alt ok nå.
