### ISSUE TITLE
"Forside" til smerteregisteret

### ISSUE THREAD

**Issue by manjan5** [manjan5/smerteregisteret#4]
Siden må opp og gå, altså en forside, pluss en fane der rapporten (og flere etter hvert som de kommer) skal ligge. Tenker at rapportene samles under en fane, ettersom det kan tenkes at det blir mange rapporter etter hvert (vi tenker oss en del smårapporter).

**Comment by areedv** [comment]
Kan gjøres ved å lage en enkel .Rmd-fil som erstatter dagens "Veiledning" (som kommer fra rapRegTemplate)

**Comment by manjan5** [comment]
Ferdig satt opp (for nå, siden vil oppdateres etter hvert som nye rapporter o.l. legges til).
